---
- hosts: 172.31.14.39
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy mytestfile into node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytest