---
- hosts: 172.31.14.39
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy mytestfile into node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytest

  - name: i want to copy index.j2 file into node side
    template:
       src: myindex.j2
       dest:  /var/www/html/index.html
    notify: restart webserver
    

  handlers:
  - name: restart webserver
    service:
        name: apache2
        state: restarted

  - name: i want to download internet files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes