---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"


  - name: i want to start web server on ubuntu node
    service:
         name: apache2
         state: started 
    when: ansible_os_family=="Debian"  

  - name: i want to install web server on redhat nodes
    dnf:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat" 

  - name: i want to start web server on redhat nodes
    service: 
       name: httpd
       state: started
    when: ansible_os_family=="RedHat""
  