---
- hosts: mywebservers
  gather_facts: yes
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"


  - name: i want to start web server on ubuntu node
    service:
         name: "{{mywebpackonubuntu}}"
         state: started 
    when: ansible_os_family=="Debian"  

  - name: i want to install web server on redhat nodes
    dnf:
      name: "{{mywebpackonRedHat}}"
      state: present
    when: ansible_os_family=="RedHat" 

  - name: i want to start web server on redhat nodes
    service: 
        name: "{{mywebpackonRedHat}}"
        state: started
    when: ansible_os_family=="RedHat"
  